### PR TITLE
chore: update to babel 6

### LINKED ISSUE #496: incompatible with projects that use Babel 6, as "loose" is now unknown option
I have a project that uses Babel 6. When I try to `require('localforage')`, I get the following babel compile error:

> ERROR in ./~/localforage/dist/localforage.js
> Module build failed: ReferenceError: [BABEL] redacted/node_modules/localforage/dist/localforage.js: Unknown option: redacted/node_modules/localforage/.babelrc.loose

The "loose" global option seems to be gone now: https://babeljs.io/docs/usage/options/

It looks like this is now supposed to be a per-plugin option, e.g: https://github.com/babel/babel/blob/6.4-stable/packages/babel-plugin-transform-es2015-for-of/test/fixtures/loose/options.json

This is loosely (pardon the pun) related to the following PRs:

- https://github.com/mozilla/localForage/pull/486
- https://github.com/mozilla/localForage/pull/390

Besides updating localForage to use Babel 6 as well, I'm not sure what other actions can be taken to resolve this.

### PR DESCRIPTION
**Pull request by thgreasi**
Resolves #496 
Also disables the Component test (which is deprecated anyway) due a change in the UMD pattern that babel6 uses.

### CODE REVIEW

**Comment by thgreasi** [comment]
We could also remove:
* the commented code in `Gruntfile.js`
* the file with the test cases
* the npm package from `package.json`

**Comment by tofumatt** [comment]
I'm for all that, we should do it here.

- tofumatt

**Comment by thgreasi** [comment]
@tofumatt Just pushed the commit that completely drops Component support.

**Comment by tofumatt** [comment]
Sweet, this looks great. Thanks!

**Pull request merged**
