### PR TITLE
Fixed typo in setItem() example

### PR DESCRIPTION
**Pull request by chrisledet**
Noticed a typo in one of the examples.

### CODE REVIEW

**Comment by tofumatt** [comment]
Good catch! `image` is probably better than `img` though... any chance you could change both to the more verbose version? :smile:

**Comment by chrisledet** [comment]
> Good catch! image is probably better than img though... any chance you could change both to the more verbose version?

No problem! This project is great by the way. Thanks!

**Comment by tofumatt** [comment]
Thanks very much, and thanks for the contribution! :+1:

**Comment by chrisledet** [comment]
Updated. Let me know if you need anything else.

**Pull request merged**
