### PR TITLE
Added documentation  for multiple instances

### LINKED ISSUE #260: Add API docs for new multiple storage feature
Since merging in #253, we should add some docs for it. :smile:

### PR DESCRIPTION
**Pull request by RangerMauve**
Added docs to both README and the site that mention the multiple instance functionality and provide an example. Fixes #260

### CODE REVIEW

**Comment by tofumatt** [comment]
Looks great! Not sure why Travis is complaining but I'll fix that then merge this in. Thanks  :+1:

**Comment by RangerMauve** [comment]
Oh weird. It seemed to work yesterday.

**Comment by tofumatt** [comment]
Yeah, I think it’s an issue with Travis or the config in it. It’s happened on other Pull Requests too but not locally. I’ll look into it :)

**Comment by RangerMauve** [comment]
Sounds good! :D

**Comment by psalaets** [comment]
The docs changes in this PR are different than what I've seen.

In my experience, only the `name` config matters for namespacing the data of localforage instances. I get errors when `name` is the same and `storeName` is different. Issue #342 may be an example of this.

As a sanity check I made an example of setting only `name`, setting only `storeName` and setting both: https://github.com/psalaets/localforage-multi-instance.

I could be missing something here, can someone double check this?

**Comment by RangerMauve** [comment]
I based the docs around the [unit tests](https://github.com/thgreasi/localForage/commit/292c4e59b9c8a7b4a813b7b67fa64a2e0147a729) that were created when this feature was added in.

To be honest, I hadn't really tested it too much myself.

The tests only reference storeName, though.

**Comment by psalaets** [comment]
Around line 399 at that link it sets `name` and `storeName`.

**Comment by RangerMauve** [comment]
So it does. I must have missed that. I'll add it in.

**Comment by tofumatt** [comment]
`name` should be considered the `database` -- in WebSQL it's the DB name and in IndexedDB it's the entire database identifier

`storeName` is a "table" or "individual store" name -- an entire app might go inside one `name` but with different model's data in each `storeName` eg like a MySQL Database with multiple tables.

Both options are available in the API in case you wanted to store everything in one DB with isolation via table/stores (this is when you would use `storeName`) or have multiple DBs via `name` to entirely encapsulate things (eg you had a library that stored data and used its own DB).

Does that make sense?

(In general, I'd say different stores in the same app might want to use the same `name` and different `storeName`s. I'm not sure what the performance implications of one over the other is though.)

**Comment by psalaets** [comment]
That sounds ideal but I haven't been able to get that to work. Whenever I set only `storeName` like this

```js
var store1 = localforage.createInstance({
  storeName: 'store1'
});

var store2 = localforage.createInstance({
  storeName: 'store2'
});
```
I get errors in Chrome and FF.

Also, it looks like the localstorage driver only uses `name` when namespacing keys. See https://github.com/mozilla/localForage/blob/master/src/drivers/localstorage.js#L62

**Comment by tofumatt** [comment]
Damn, that's not good.

Also, I know that newer versions have had issues with `createInstance`, see: #342.

**Comment by perlun** [comment]
@psalaets - I see the same thing that you do. When I override the `name`, that takes effect as in overriding the IndexedDB database name (Chrome Canary). When I also try to set the storeName to the name of the "table" (instead of keyvaluepairs), I get these exceptions:

```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Error (native)
    at http://localhost:4200/assets/vendor.js:74803:45
```

Using localforage 1.2.2, installed via Bower. I assume there is some hardwiredness to `keyvaluepairs` somewhere...

**Comment by perlun** [comment]
Doesn't seem like it, so then it's probably a matter of things happening in an unexpected order or similar.

**Comment by perlun** [comment]
The same error here, but no insight into the reason: http://stackoverflow.com/questions/26473502/cannot-create-second-objectstore-indexeddb

**Comment by perlun** [comment]
This one is really fishy. I've checked the tests in `localForage` and they very much set the `storeName` to a custom value - and it works! Whenever I try to use it from my own app (setting up some fixture data in my QUnit `setup` handler), things go berserk and I get the exceptions mentioned above.

Ideas, anyone?

**Comment by psalaets** [comment]
@perlun The multi-instance tests set `name` *and* `storeName` which works because setting `name` to unique values prevents the issue.

I'm referring to https://github.com/mozilla/localForage/blob/master/test/test.api.js#L639.

There the two instances are the default localforage instance which uses `{name: 'localforage', storeName: 'keyvaluepairs'}` and `localforage2` which uses `{name: 'storage2', storeName: 'storagename2'}`.

Are there other tests I'm forgetting that only set `storeName`?

**Comment by perlun** [comment]
Thanks. You are right, it's when you try to use the same `name` but with different `storeName` you get this. I debugged this quite a bit yesterday - #374 has the details.

**Comment by thgreasi** [comment]
Should we merge this? After a restart on travis the tests passed.
I would just suggest to change the `storeName` to just `name` since there still is the "multiple instances with same storeName" #342 issue.
We should also mention that you can pass all the `config` options.

**Comment by thgreasi** [comment]
@RangerMauve can you do a rebase? In all my merge attempts your initial commit & authorship gets lost.

**Comment by thgreasi** [comment]
@RangerMauve Just opened #442 that resolves conflicts and merges this.
No need to rebase yourself.
Any feedback is welcome.

**Comment by RangerMauve** [comment]
Sorry for the late reply! I currently don't have stable access to the internet. Glad to see this merged in, though! :D

**Pull request merged**
