### PR TITLE
Updated README regarding TypeScript usage

### PR DESCRIPTION
**Pull request by dsebastien**
See discussion in #494

### CODE REVIEW

**Comment by tofumatt** [comment]
I don't know really anything about typescript, but why declare it as a constant?

**Comment by dsebastien** [comment]
I feels safer to me, although I'm no TypeScript guru either ;-))

**Comment by tofumatt** [comment]
If there's no clear reason to do it, let's not make it a constant without understanding the ramifications. But after that fix I'd say we're good to merge, thanks :-)

- tofumatt

**Comment by dsebastien** [comment]
let and const have been supported in TypeScript since version 1.5 and can be transpiled down to ES3 & ES5, thus logically this should not have any negative effects.

AFAIK, using let and const is the way to go; var should never be used anymore and here, the choice between let and const depends on whether you want something mutable or not; for an import I'd say that const is probably a safer recommendation.

If you want maybe I can add this explanation to the readme?

**Comment by tofumatt** [comment]
Okay, that makes sense.

The readme is busy enough so it's okay, but I'll keep it in mind when I get the chance to fix up the docs (an idea I have for the future).

- tofumatt (Sent from mobile)

**Pull request merged**
