### PR TITLE
fix for issue #365

### PR DESCRIPTION
**Pull request by marcucio**
When I am running my qunit tests using karma I am getting this error when loading localforage library:

ReferenceError: Can't find variable: require

The issue is that qunit defines "module" and "module.exports" so this check we have passes (but require is undefined)

 if (typeof module !== 'undefined' && module.exports)
I have a fix for it, changing it to:

if (typeof module !== 'undefined' && module.exports && typeof require !== 'undefined')
fixes the issue. There might be a different fix when I set up karma or qunit but I didn't find one, and it might be good to check for require before using it.

### CODE REVIEW

**Comment by tofumatt** [comment]
Looks like you've got a style error: https://travis-ci.org/mozilla/localForage/builds/55992720

Try running `npm test` to run the entire test suite, then push a fix?

**Comment by marcucio** [comment]
interesting, I didn't change that part of the code and ```npm test``` works on my system:

```
Michaels-MacBook-Pro:localForage mike$ npm test

> localforage@1.2.2 test /Users/mike/Projects/localForage
> grunt test

Running "concat:localforage" (concat) task
File "dist/localforage.js" created.
File "dist/localforage.nopromises.js" created.

Running "es3_safe_recast:dist" (es3_safe_recast) task
Compiled ES3 Safe Recast: "dist/localforage.js
Saved compiled file(s) at: dist/localforage.js

Running "es3_safe_recast:nopromises" (es3_safe_recast) task
Compiled ES3 Safe Recast: "dist/localforage.nopromises.js
Saved compiled file(s) at: dist/localforage.nopromises.js

Running "uglify:localforage" (uglify) task
File dist/localforage.min.js created: 82.05 kB → 22.98 kB
File dist/localforage.nopromises.min.js created: 63.04 kB → 17.8 kB
File site/localforage.min.js created: 82.05 kB → 22.98 kB

Running "jshint:source" (jshint) task
>> 15 files lint free.

Running "jscs:source" (jscs) task
>> 15 files without code style errors.

Running "shell:component" (shell) task

       build : resolved in 15ms
       build : files in 18ms
       build : test/localforage.component.js in 19ms - 83kb


Running "connect:test" (connect) task
Started connect web server on http://0.0.0.0:9999

Running "mocha:unit" (mocha) task
Testing: http://localhost:9999/test/test.component.html

  
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  177 passing (1s)
  7 pending

Testing: http://localhost:9999/test/test.nodriver.html

  
  ․․․․․․․․․․․․

  12 passing (304ms)

Testing: http://localhost:9999/test/test.main.html

  
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  177 passing (3s)
  7 pending

Testing: http://localhost:9999/test/test.min.html

  
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  177 passing (3s)
  7 pending

Testing: http://localhost:9999/test/test.require.html

  
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  177 passing (4s)
  7 pending

Testing: http://localhost:9999/test/test.callwhenready.html

  
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․

  168 passing (6s)
  7 pending

Testing: http://localhost:9999/test/test.customdriver.html

  
  ․․․․․․․․․․․․

  12 passing (303ms)

>> 935 passed! (18.49s)

Done, without errors.
```

**Comment by havok2905** [comment]
That formatting bug in question has already been fixed with the following commit. I imagine performing a rebase from master would clean that up. If not a rebase, dropping the comments under the function declaration satisfies the linter.

https://github.com/mozilla/localForage/commit/5e0df09bce8f0316369c05a867b0d5d7b836fb8f

**Comment by tofumatt** [comment]
Updated in #378.

**Pull request closed without merging**
