### PR TITLE
Fix iterate in localstorage issue 407

### LINKED ISSUE #407: localStorage driver iterate function fetches items which are not owned by localforage db
I found this issue when localforage is used in an environment where browser is IE and when localforage is using localStorage driver.

I think issue is localforage assumes entire localstorage is owned by itself which is not the case in certain applications, some other javascripts and apps can use same localstorage to store their values. So localforage must not assume and work as its own entire localstorage and its data. 

Check the following iterate method

https://github.com/mozilla/localForage/blob/master/src/drivers/localstorage.js#L102
~~~js
    function iterate(iterator, callback) {
        var self = this;

        var promise = self.ready().then(function() {
            var keyPrefix = self._dbInfo.keyPrefix;
            var keyPrefixLength = keyPrefix.length;
            var length = localStorage.length;

            for (var i = 0; i < length; i++) {
                var key = localStorage.key(i);
                var value = localStorage.getItem(key);

                // If a result was found, parse it from the serialized
                // string into a JS object. If result isn't truthy, the
                // key is likely undefined and we'll pass it straight
                // to the iterator.
                if (value) {
                    value = serializer.deserialize(value);
                }

                value = iterator(value, key.substring(keyPrefixLength), i + 1);

                if (value !== void(0)) {
                    return value;
                }
            }
        });

        executeCallback(promise, callback);
        return promise;
    }
~~~
After `var key = localStorage.key(i);` it should check whether key is related to its data before fetching the value. This check has been done in other methods. It should not deserialize the item if it is not stored by localforage (simply someone else' data) which could throw exceptions and unpredictable behaviours, Moreover caller of this library expect to get data what it stored using localforage, not all the data stored in browser localstorage.

### PR DESCRIPTION
**Pull request by tofumatt**
Adds a test and fixes a minor whitespace fix from #418.

Fixes #407.

### CODE REVIEW

**Comment by af7** [comment]
Hello Matthew,

I am not sure if it is totally needed, but you have this final code on the other tests while you do not have it on this test:

`localStorage.clear();`

FYI, this is what I did for a test (I will not do a PR now obviously):
https://github.com/af7/localForage/commit/229d30709f02d7b56faf5a0c2087c959c0c082c3

Thanks.

**Comment by af7** [comment]
Also, in your website docs, you call the argument of the `successCallback` as `result` but you use it as `error` on the test.

This is what you have on the Docs...

````
// Exit the iteration early:
localforage.iterate(function(value, key, iterationNumber) {
    if (iterationNumber < 3) {
        console.log([key, value]);
    } else {
        return [key, value];
    }
}, function(result) {
    console.log('Iteration has completed, last iterated pair:');
    console.log(result);
});
````

...and this is what you use on the Test:

````
}, function(err) {
     if (!err) {
````

**Comment by tofumatt** [comment]
It isn't needed in that test (it might not even be needed in the other ones actually, as localForage should always stick to its own namespace and not need to clean out ALL of localStorage).

Our tests are pretty similar, thanks for sharing. As you see: it's more about checking to make sure "out-of-bounds" items _don't_ get returned than checking for what is returned.

Thanks!

**Comment by tofumatt** [comment]
You're right, though that's a separate issue. I'll check into that...

**Comment by tofumatt** [comment]
fwiw, looks like that’s an error in the docs. I will fix it and push that now. Thanks for catching it!

- tofumatt

**Comment by af7** [comment]
Concerning the `localStorage.clear();` question, I thought that this is done so that the **next** test starts with a clean localStorage environment (which is needed for proper testing). This is why I though it is kind of necessary.

It seems that tests that need this *clean* environment could start with `localStorage.clear();`, so that you do not have to do this at the end of each test. In any case, you know much better what needs to be done (or not).

Thanks again!

**Comment by tofumatt** [comment]
Turns out localStorage.clear() is run in the `beforeEach` block. That clear() in the actual method might even be legacy.


Thanks for reporting. :-)


- tofumatt

**Pull request merged**
