### PR TITLE
move .babelrc closer to files it governs

### PR DESCRIPTION
**Pull request by jokeyrhyme**
- may be an interim solution to #496 
- affects projects that consume the default package "main", or other files in the "dist" directory
- for such projects that use babel themselves, the .babelrc for localforage will no longer be in scope

### CODE REVIEW

**Comment by tofumatt** [comment]
I know @thgreasi said he was working on a fix for this, so an interim fix might be a bit hasty.

How does this affect current users exactly? I don't understand the bit about users using `package.json`'s `main`--will they have to change configs?

In that case it's just a big enough/breaking change that will require a bump to `1.4`.

**Comment by jokeyrhyme** [comment]
There's no breaking change.

> affects projects that consume the default package "main"

By this I mean projects that just `import localforage from 'localforage';` (the designated "main" file in package.json).

>  or other files in the "dist" directory

By this I mean projects that `import localforage from 'localforage/dist/localforage.nopromises';` (for example)

No consuming project has to make any changes as a consequence of this. In fact, this allows more consuming projects to build correctly with babel.

**Comment by jokeyrhyme** [comment]
The only downside (if any) is that all files in this project that need babel MUST be located within the "src" directory. As this is already the case, and is likely to be the case for the foreseeable future, it doesn't seem like such bad limitation.

**Comment by tofumatt** [comment]
Ah, cool. Sorry I misunderstood.

Looks good then, I’ll merge this in a few ^_^

**Comment by tofumatt** [comment]
Actually, this isn't what we'd want, as if we wanted to start using ES6 for tests (which I personally would), it wouldn't be covered. Other projects I work on keep the `.babelrc` in the root of the project, that seems correct. So this seems quite temporary, I'm torn :-/

**Comment by jokeyrhyme** [comment]
Yeah, it's definitely a weird compromise. Thought I'd run this past you anyhow and see what people thought. Having a second .babelrc in the "test" directory also seems weird.

As you say, this is of limited benefit once babel 6 is supported.

**Comment by jokeyrhyme** [comment]
Actually, even once babel 6 is supported, there'll still be some theoretical value here.

In babel 6, the "loose" option was dropped (well, moved) which made old .babelrc files throw errors. If babel 7 (for example) similarly breaks when it reads .babelrc files for babel 6, then we'll just run into the same problem next time.

Ideally, we want the files that are babel'ed here already (those in "dist") to have nothing to do with babel.

**Comment by thgreasi** [comment]
:+1:
Didn't know you could do such a thing!
If it works as I think then it might be even better than removing the
.babelrc file from the npm package. Since package.json's main targets the
dist files, trying to force everyone to use a single import method, this
could conceal the use of babel, except from those that manually target the
src files.

Ps: I guess that this is not affecting the build at all?

Ps2: I won't be able to resume the upgrade to babel 6 until early next
month :(

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by tofumatt** [comment]
Looks like the issue this meant to fix has been resolved, this commit is out of date, and I think we want to close this.

Thanks for the patch but I think this is fixed now? Please let me know if I'm wrong to close.

**Comment by jokeyrhyme** [comment]
If we're using the latest babel now, then there's no need for this.

**Pull request closed without merging**
