### PR TITLE
fix for bug where we were going into an infinite loop on fail

### PR DESCRIPTION
**Pull request by marcucio**
fix for bug where we were going into an infinite loop if the open database failed (saw this on BB10 cordova app)

I don't think we should call _initStorage again since it just failed

### CODE REVIEW

**Comment by tofumatt** [comment]
Odd that it goes into an infinite loop when we explicitly choose localStorage, which should then just reject again and then stop on failure, right?

**Comment by tofumatt** [comment]
It would be handy to include a test that checks for this if we decide to merge it in so we don't revert it in the future. I saw you had an example in #511 -- could you add that to the tests for this PR?

**Comment by marcucio** [comment]
ok, I'll see if I can come up with a test for this, it might be a few days since I'm trying to get a release out for one of my apps.

**Comment by marcucio** [comment]
@thgreasi @tofumatt 
I integrated test cases from #515 into this pull request, everything seems good to go. One question, should I also check in the dist files?

**Comment by thgreasi** [comment]
Add the dist files as well.
How about pulling or rebasing the test case instead of copying?

**Comment by marcucio** [comment]
sorry, I'm not sure how to merge a pull request from this fork into my fork, I will have to look into how to do that.

I just checked in dist files so that should be good to go too.

**Comment by marcucio** [comment]
@thgreasi @tofumatt I think this should be all set to merge, I merged the #515 in to this request

**Comment by thgreasi** [comment]
Great :+1:
I guess that this should be released with a new minor version change, since there might be people that relied on the hidden websql->localStorage fallback mechanism.

**Comment by thgreasi** [comment]
Also :+1: for adding the dist files as a separate commit!

**Comment by tofumatt** [comment]
Looks good, I may try to squash a few of these commits before I merge and it’s getting late here, so I might not get to this until tomorrow, but rest assured I’m on it! Thanks!

**Comment by tofumatt** [comment]
Merged in #517 with some tidying.

**Pull request closed without merging**
