### PR TITLE
Fix for #304

### PR DESCRIPTION
**Pull request by irukavina**
Add check if the config() was called with not-a-number version
parameter and the corresponding test

### CODE REVIEW

**Comment by tofumatt** [comment]
This is good but I think it would be even better to try to cast the string to a number first. So things like `'2.0'` become `2.0`. Otherwise I think we're effectively breaking the API (even if using it wrongly resulted in a different error).

Do you think we could try casting a string value first?

**Comment by irukavina** [comment]
You're right - I'll modify the code and update the PR.

**Comment by irukavina** [comment]
One thing that gives me concern is the following scenario: 

Imagine someone creating a WebSQL storage with localForage. One of the used options is version:
```
dbInfo.db = openDatabase(dbInfo.name, String(dbInfo.version),
                                         dbInfo.description, dbInfo.size);
```

If the casting fix is added, the version parameter would be first cast to a float, and then recast as a string. Thus, before the fix, if the version was 13.0a, openDatabase will be called like this:
```
openDatabase(_, '13.0a', _, _)  // no casting here
```
and after the proposed fix openDatabase would be called like this:
```
openDatabase(_, '13', _, _) // String(parseFloat('13.0a')) -> '13'
```

This call will result in an error since there is no db.changeVersion in the localForage's WebSQL driver: 
```
unable to open database, version mismatch, '13' does not match the currentVersion of '13.0a'
```

I think that either: 
- the check if float is not a number should be a bit smarter, throwing an error if there are characters that are not standard in a number (for example, alphanumerics) 

- a breaking change in the API will have to be added

Can you share your thoughts on this? 

Thanks

**Comment by tofumatt** [comment]
Hmmm, I guess I'd rather the check be smart and only allow version strings that **all** drivers could use and didn't fail on.

If that requires a breaking change or even a version release with a deprecation then another with the breaking change I'm cool with that.

**Pull request closed without merging**
