### PR TITLE
Fix localStorage iterate method

### PR DESCRIPTION
**Pull request by af7**
Related to issue #407

### CODE REVIEW

**Comment by tofumatt** [comment]
Thanks! (Was it really that simple, haha?)

Would you be able to write a test for this?

**Comment by thgreasi** [comment]
I think we already have a similar test for the keys() method. We could
probably use the same for iterate().

On Thu, Aug 13, 2015, 18:15 Matthew Riley MacPherson <
notifications@github.com> wrote:

> Thanks! (Was it really that simple, haha?)
>
> Would you be able to write a test for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/pull/418#issuecomment-130725914>.
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
[This is the test I was talking about](https://github.com/mozilla/localForage/blob/3257d192e47d553f789fe62007f3e6d46aa4b04b/test/test.api.js#L529-L541).

**Comment by tofumatt** [comment]
Oh, nice. Okay, I'm just coming home from the gym. I can do that test in a few hours tops.



- tofumatt

**Pull request closed without merging**
